# Generated by Django 2.2.5 on 2019-12-06 01:43

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jersey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=30)),
                ('country', models.CharField(blank=True, max_length=20)),
                ('manufacturer', models.CharField(choices=[('Adidas', 'Adidas'), ('Nike', 'Nike'), ('Puma', 'Puma'), ('Umbro', 'Umbro'), ('New Balance', 'New Balance'), ('Hummel', 'Hummel'), ('Under Armour', 'Under Armour'), ('Kappa', 'Kappa'), ('Macron', 'Macron'), ('Joma', 'Joma'), ('Other', 'Other')], max_length=20)),
                ('size', models.CharField(max_length=20)),
                ('primary_color', models.CharField(blank=True, max_length=20)),
                ('authentic', models.BooleanField(blank=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
            ],
            managers=[
                ('Jerseys', django.db.models.manager.Manager()),
            ],
        ),
    ]
